# Generated by Django 3.1.7 on 2021-05-17 11:45

import admin_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0004_auto_20210516_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='image',
        ),
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.ImageField(blank=True, default='book-cover/book-default.png', null=True, upload_to=admin_user.models.user_directory_path),
        ),
    ]
