# Generated by Django 3.1.7 on 2021-05-10 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_user.members')),
            ],
        ),
        migrations.CreateModel(
            name='detail_transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_returned', models.CharField(max_length=1)),
                ('return_of_date', models.DateField(null=True)),
                ('is_ontime', models.CharField(max_length=1, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_user.books')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transaction.transactions')),
            ],
        ),
    ]
