# Generated by Django 3.1.7 on 2021-05-16 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detail_transactions',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ['id']},
        ),
    ]
